language: python
install:
  - pip install tox 
script:
  - tox
env:
  - TOXENV=py27-django16
  - TOXENV=py27-django17
  - TOXENV=py27-django18
  - TOXENV=py27-django19
  - TOXENV=py27-django110
  - TOXENV=py27-django111
  - TOXENV=py36-django18
  - TOXENV=py36-django19
  - TOXENV=py36-django110
  - TOXENV=py36-django111
  - TOXENV=py36-django20
